walenty(adaptacja , do , gen ).
walenty(adaptacja , pod , acc ).
walenty(afera , o , acc ).
walenty(afera , wokół , gen ).
walenty(afera , z , gen ).
walenty(agresja , na , acc ).
walenty(agresja , przeciw , dat ).
walenty(agresja , wobec , gen ).
walenty(akceptacja , dla , gen ).
walenty(akceptacja , przez , acc ).
walenty(akceptacja , w , loc ).
walenty(akcja , przeciw , dat ).
walenty(akcyza , na , acc ).
walenty(akcyza , od , gen ).
walenty(alarm , dla , gen ).
walenty(alarm , o , loc ).
walenty(album , na , acc ).
walenty(album , o , loc ).
walenty(album , z , inst ).
walenty(alians , między , inst ).
walenty(alians , przeciw , dat ).
walenty(alians , z , inst ).
walenty(alternatywa , dla , gen ).
walenty(alternatywa , między , inst ).
walenty(alternatywa , wobec , gen ).
walenty(alternatywa , względem , gen ).
walenty(amator , na , acc ).
walenty(amator , w , loc ).
walenty(anegdota , o , loc ).
walenty(aneks , do , gen ).
walenty(aneks , na , acc ).
walenty(aneks , o , loc ).
walenty(apel , do , gen ).
walenty(apel , o , acc ).
walenty(apel , przeciw , dat ).
walenty(apetyt , na , acc ).
walenty(aprobata , dla , gen ).
walenty(aprobata , na , acc ).
walenty(argument , na , acc ).
walenty(argument , o , loc ).
walenty(argument , przeciw , dat ).
walenty(argument , za , inst ).
walenty(argument , z , inst ).
walenty(artykuł , o , loc ).
walenty(aspiracja , do , gen ).
walenty(aspiracja , na , acc ).
walenty(aspiracja , wobec , gen ).
walenty(aspiracja , względem , gen ).
walenty(aspirant , do , gen ).
walenty(atak , na , acc ).
walenty(atak , przeciw , dat ).
walenty(autonomia , dla , gen ).
walenty(autonomia , przy , loc ).
walenty(autonomia , w , loc ).
walenty(autonomia , wobec , gen ).
walenty(autonomia , względem , gen ).
walenty(awantura , między , inst ).
walenty(awantura , o , acc ).
walenty(awantura , z , inst ).
walenty(badanie , dla , gen ).
walenty(badanie , na , acc ).
walenty(badanie , nad , inst ).
walenty(badanie , przeciw , dat ).
walenty(bajka , dla , gen ).
walenty(bajka , o , loc ).
walenty(ballada , dla , gen ).
walenty(ballada , o , loc ).
walenty(ballada , przeciw , dat ).
walenty(baśń , dla , gen ).
walenty(baśń , o , loc ).
walenty(batalia , między , inst ).
walenty(batalia , na , acc ).
walenty(batalia , na , loc ).
walenty(batalia , o , acc ).
walenty(batalia , przeciw , dat ).
walenty(batalia , za , acc ).
walenty(batalia , za , inst ).
walenty(batalia , z , inst ).
walenty(baza , dla , gen ).
walenty(baza , do , gen ).
walenty(baza , pod , acc ).
walenty(bilet , do , gen ).
walenty(bilet , na , acc ).
walenty(bitwa , między , inst ).
walenty(bitwa , na , acc ).
walenty(bitwa , o , acc ).
walenty(bitwa , przeciw , dat ).
walenty(bitwa , z , inst ).
walenty(bliskość , do , gen ).
walenty(bliskość , między , inst ).
walenty(bliskość , od , gen ).
walenty(bliskość , wobec , gen ).
walenty(bliskość , względem , gen ).
walenty(bliskość , z , inst ).
walenty(błogosławieństwo , dla , gen ).
walenty(błogosławieństwo , na , acc ).
walenty(błogosławieństwo , nad , inst ).
walenty(błogosławieństwo , za , acc ).
walenty(bodziec , dla , gen ).
walenty(bodziec , do , gen ).
walenty(bój , między , inst ).
walenty(bój , na , acc ).
walenty(bój , o , acc ).
walenty(bój , przeciw , dat ).
walenty(bój , za , acc ).
walenty(bój , z , inst ).
walenty(ból , od , gen ).
walenty(ból , po , loc ).
walenty(ból , w , loc ).
walenty(brama , do , gen ).
walenty(brama , na , acc ).
walenty(brama , od , gen ).
walenty(bunt , na , acc ).
walenty(bunt , przeciw , dat ).
walenty(bunt , wobec , gen ).
walenty(bunt , względem , gen ).
walenty(cel , do , gen ).
walenty(cel , na , acc ).
walenty(cena , za , acc ).
walenty(chęć , dla , gen ).
walenty(chęć , do , gen ).
walenty(chęć , na , acc ).
walenty(chwila , na , acc ).
walenty(chwyt , do , gen ).
walenty(chwyt , na , acc ).
walenty(chwyt , przez , acc ).
walenty(chwyt , za , acc ).
walenty(cień , do , gen ).
walenty(cierpienie , od , gen ).
walenty(cierpienie , po , loc ).
walenty(cierpienie , za , acc ).
walenty(cierpliwość , do , gen ).
walenty(cierpliwość , w , loc ).
walenty(cierpliwość , wobec , gen ).
walenty(cierpliwość , względem , gen ).
walenty(cisza , wokół , gen ).
walenty(cokolwiek , z , gen ).
walenty(coś , z , gen ).
walenty(co , z , gen ).
walenty(cóż , z , gen ).
walenty(cześć , dla , gen ).
walenty(część , dla , gen ).
walenty(część , do , gen ).
walenty(część , o , loc ).
walenty(cześć , z , gen ).
walenty(część , z , gen ).
walenty(członkostwo , w , loc ).
walenty(czujność , wobec , gen ).
walenty(czujność , wśród , gen ).
walenty(czujność , względem , gen ).
walenty(czułość , dla , gen ).
walenty(czułość , do , gen ).
walenty(czułość , między , inst ).
walenty(czułość , na , acc ).
walenty(czułość , wobec , gen ).
walenty(czułość , wśród , gen ).
walenty(czułość , względem , gen ).
walenty(dana , o , loc ).
walenty(dar , dla , gen ).
walenty(dar , do , gen ).
walenty(dar , na , acc ).
walenty(dar , od , gen ).
walenty(dbałość , o , acc ).
walenty(dbałość , przy , loc ).
walenty(dbałość , w , loc ).
walenty(dbałość , wobec , gen ).
walenty(dbałość , względem , gen ).
walenty(debata , między , inst ).
walenty(debata , nad , inst ).
walenty(debata , o , loc ).
walenty(debata , wokół , gen ).
walenty(debata , wśród , gen ).
walenty(debata , z , inst ).
walenty(decyzja , o , loc ).
walenty(decyzja , przeciw , dat ).
walenty(decyzja , za , inst ).
walenty(deklaracja , o , loc ).
walenty(dekoracja , do , gen ).
walenty(dekoracja , przez , acc ).
walenty(dekret , o , loc ).
walenty(dekret , przeciw , dat ).
walenty(delegacja , dla , gen ).
walenty(delegacja , do , gen ).
walenty(delegacja , na , acc ).
walenty(delegacja , o , loc ).
walenty(delegacja , za , acc ).
walenty(delegat , do , gen ).
walenty(delegat , na , acc ).
walenty(determinacja , do , gen ).
walenty(determinacja , w , loc ).
walenty(dialog , między , inst ).
walenty(dialog , o , loc ).
walenty(dialog , przeciw , dat ).
walenty(dialog , z , inst ).
walenty(dochód , dla , gen ).
walenty(dochód , na , acc ).
walenty(dochód , od , gen ).
walenty(dochód , poniżej , gen ).
walenty(dochód , powyżej , gen ).
walenty(dochód , za , acc ).
walenty(dochód , z , gen ).
walenty(dodatek , dla , gen ).
walenty(dodatek , do , gen ).
walenty(dodatek , na , acc ).
walenty(dodatek , o , loc ).
walenty(dodatek , za , acc ).
walenty(doktryna , o , loc ).
walenty(doktryna , przeciw , dat ).
walenty(doktryna , w , loc ).
walenty(doktryna , wobec , gen ).
walenty(doktryna , względem , gen ).
walenty(dokument , o , loc ).
walenty(dominacja , nad , inst ).
walenty(dominacja , w , loc ).
walenty(domysł , o , loc ).
walenty(donos , na , acc ).
walenty(donos , o , loc ).
walenty(donos , przeciw , dat ).
walenty(doping , do , gen ).
walenty(doping , w , loc ).
walenty(dopisek , do , gen ).
walenty(dopisek , o , loc ).
walenty(dostęp , do , gen ).
walenty(dostęp , przez , acc ).
walenty(doświadczenie , nad , inst ).
walenty(doświadczenie , na , loc ).
walenty(doświadczenie , o , loc ).
walenty(doświadczenie , w , loc ).
walenty(doświadczenie , z , gen ).
walenty(doświadczenie , z , inst ).
walenty(dowcip , o , loc ).
walenty(dowód , na , acc ).
walenty(dowód , przeciw , dat ).
walenty(dowód , za , inst ).
walenty(dowództwo , nad , inst ).
walenty(dozór , dla , gen ).
walenty(dozór , nad , inst ).
walenty(dozór , przez , acc ).
walenty(dozór , wobec , gen ).
walenty(dozór , względem , gen ).
walenty(dozór , za , acc ).
walenty(drzwi , do , gen ).
walenty(drzwi , na , acc ).
walenty(drzwi , od , gen ).
walenty(duma , z , gen ).
walenty(dyrektywa , dla , gen ).
walenty(dyrektywa , do , gen ).
walenty(dyrektywa , o , loc ).
walenty(dyskusja , między , inst ).
walenty(dyskusja , nad , inst ).
walenty(dyskusja , o , loc ).
walenty(dyskusja , z , inst ).
walenty(dziura , po , loc ).
walenty(dziura , w , loc ).
walenty(efekt , dla , gen ).
walenty(efekt , w , loc ).
walenty(egzamin , do , gen ).
walenty(egzamin , na , acc ).
walenty(egzamin , po , loc ).
walenty(egzamin , z , gen ).
walenty(eksperyment , na , loc ).
walenty(eksperyment , z , gen ).
walenty(eksperyment , z , inst ).
walenty(ekstrakt , z , gen ).
walenty(entuzjazm , dla , gen ).
walenty(entuzjazm , do , gen ).
walenty(entuzjazm , w , loc ).
walenty(entuzjazm , wobec , gen ).
walenty(entuzjazm , względem , gen ).
walenty(entuzjazm , z , gen ).
walenty(epoka , w , loc ).
walenty(fachowiec , od , gen ).
walenty(fachowiec , w , loc ).
walenty(fakt , przeciw , dat ).
walenty(fakt , za , inst ).
walenty(faul , na , loc ).
walenty(faworyt , do , gen ).
walenty(faworyt , na , acc ).
walenty(faworyt , w , loc ).
walenty(fragment , o , loc ).
walenty(fragment , z , gen ).
walenty(fuzja , między , inst ).
walenty(fuzja , z , inst ).
walenty(gest , wobec , gen ).
walenty(gest , względem , gen ).
walenty(głos , na , acc ).
walenty(głos , o , loc ).
walenty(głos , przeciw , dat ).
walenty(głos , za , inst ).
walenty(gniew , między , inst ).
walenty(gniew , na , acc ).
walenty(gniew , przeciw , dat ).
walenty(gniew , wobec , gen ).
walenty(gniew , wśród , gen ).
walenty(gniew , względem , gen ).
walenty(gniew , za , acc ).
walenty(gorycz , do , gen ).
walenty(gotowość , do , gen ).
walenty(gotowość , na , acc ).
walenty(gotowość , w , loc ).
walenty(gra , dla , gen ).
walenty(gra , do , gen ).
walenty(gra , na , acc ).
walenty(gra , na , loc ).
walenty(granica , między , inst ).
walenty(granica , z , inst ).
walenty(gra , o , acc ).
walenty(gra , o , loc ).
walenty(gra , w , acc ).
walenty(gra , w , loc ).
walenty(gra , z , gen ).
walenty(gra , z , inst ).
walenty(grunt , dla , gen ).
walenty(grunt , do , gen ).
walenty(grunt , pod , acc ).
walenty(grzech , przeciw , dat ).
walenty(grzech , wobec , gen ).
walenty(gwarancja , dla , gen ).
walenty(gwarancja , na , acc ).
walenty(hańba , dla , gen ).
walenty(hańba , na , loc ).
walenty(hasło , dla , gen ).
walenty(hasło , do , gen ).
walenty(hasło , o , loc ).
walenty(hasło , przeciw , dat ).
walenty(hasło , za , inst ).
walenty(historia , o , loc ).
walenty(idea , na , acc ).
walenty(informacja , dla , gen ).
walenty(informacja , do , gen ).
walenty(informacja , od , gen ).
walenty(informacja , o , loc ).
walenty(integracja , między , inst ).
walenty(integracja , przeciw , dat ).
walenty(integracja , wokół , gen ).
walenty(integracja , wśród , gen ).
walenty(integracja , z , inst ).
walenty(interes , dla , gen ).
walenty(interes , na , loc ).
walenty(interes , w , loc ).
walenty(interes , z , inst ).
walenty(intuicja , wobec , gen ).
walenty(intuicja , względem , gen ).
walenty(irytacja , na , acc ).
walenty(irytacja , wobec , gen ).
walenty(irytacja , względem , gen ).
walenty(irytacja , za , acc ).
walenty(kampania , o , acc ).
walenty(kampania , o , loc ).
walenty(kampania , przeciw , dat ).
walenty(kampania , za , inst ).
walenty(kandydat , do , gen ).
walenty(kandydat , na , acc ).
walenty(kandydat , przeciw , dat ).
walenty(kara , dla , gen ).
walenty(kara , za , acc ).
walenty(kartka , na , acc ).
walenty(kartka , z , inst ).
walenty(kierownictwo , nad , inst ).
walenty(kierunek , na , loc ).
walenty(kierunek , w , loc ).
walenty(kłamstwo , o , loc ).
walenty(kłamstwo , przeciw , dat ).
walenty(kłamstwo , przed , inst ).
walenty(kłamstwo , wobec , gen ).
walenty(kłamstwo , wokół , gen ).
walenty(kłamstwo , względem , gen ).
walenty(kłopot , dla , gen ).
walenty(kłopot , w , loc ).
walenty(kłopot , z , inst ).
walenty(klucz , dla , gen ).
walenty(klucz , do , gen ).
walenty(klucz , na , acc ).
walenty(klucz , od , gen ).
walenty(kolejka , do , gen ).
walenty(kolejka , na , acc ).
walenty(kolejka , po , acc ).
walenty(kolejka , po , loc ).
walenty(kolejka , za , inst ).
walenty(kolej , na , acc ).
walenty(kolejność , w , loc ).
walenty(komenda , dla , gen ).
walenty(komenda , do , gen ).
walenty(komenda , nad , inst ).
walenty(komenda , od , gen ).
walenty(komentarz , dla , gen ).
walenty(komentarz , do , gen ).
walenty(komentarz , o , loc ).
walenty(komisja , do , gen ).
walenty(kompetencja , do , gen ).
walenty(kompetencja , w , loc ).
walenty(kompetencja , względem , gen ).
walenty(komunikacja , między , inst ).
walenty(komunikacja , o , loc ).
walenty(komunikacja , z , inst ).
walenty(koncepcja , na , acc ).
walenty(koncepcja , o , loc ).
walenty(koncert , na , acc ).
walenty(koncert , z , inst ).
walenty(konflikt , między , inst ).
walenty(konflikt , o , acc ).
walenty(konflikt , wokół , gen ).
walenty(konflikt , z , inst ).
walenty(koniec , z , inst ).
walenty(konsekwencja , dla , gen ).
walenty(konsekwencja , w , loc ).
walenty(kontrola , nad , inst ).
walenty(kontrola , wobec , gen ).
walenty(kontrola , względem , gen ).
walenty(konwencja , dla , gen ).
walenty(konwencja , między , inst ).
walenty(konwencja , o , loc ).
walenty(konwencja , przeciw , dat ).
walenty(kpina , wobec , gen ).
walenty(kpina , względem , gen ).
walenty(kpina , z , gen ).
walenty(kredyt , dla , gen ).
walenty(kredyt , na , acc ).
walenty(kredyt , od , gen ).
walenty(kredyt , z , gen ).
walenty(krok , do , gen ).
walenty(krok , ku , dat ).
walenty(krok , w , loc ).
walenty(kryterium , na , acc ).
walenty(krytyka , wobec , gen ).
walenty(krytyka , względem , gen ).
walenty(krytyka , za , acc ).
walenty(krzyk , do , gen ).
walenty(krzyk , o , acc ).
walenty(krzyk , wokół , gen ).
walenty(książka , dla , gen ).
walenty(książka , do , gen ).
walenty(książka , o , loc ).
walenty(książka , przeciw , dat ).
walenty(książka , z , gen ).
walenty(księga , dla , gen ).
walenty(księga , ku , dat ).
walenty(księga , o , loc ).
walenty(kurs , dla , gen ).
walenty(kurs , do , gen ).
walenty(kurs , na , acc ).
walenty(kurs , wobec , gen ).
walenty(kurs , względem , gen ).
walenty(kurs , z , gen ).
walenty(kwalifikacje , do , gen ).
walenty(kwalifikacje , w , loc ).
walenty(kwalifikacje , z , gen ).
walenty(kwestia , o , loc ).
walenty(kwestia , w , loc ).
walenty(legenda , o , loc ).
walenty(legenda , wokół , gen ).
walenty(lek , dla , gen ).
walenty(lek , na , acc ).
walenty(lęk , o , acc ).
walenty(lek , przeciw , dat ).
walenty(lęk , przed , inst ).
walenty(lęk , wobec , gen ).
walenty(list , dla , gen ).
walenty(list , do , gen ).
walenty(list , od , gen ).
walenty(list , o , loc ).
walenty(list , przeciw , dat ).
walenty(list , za , inst ).
walenty(lot , na , loc ).
walenty(małżeństwo , między , inst ).
walenty(małżeństwo , z , inst ).
walenty(mandat , dla , gen ).
walenty(mandat , do , gen ).
walenty(mandat , na , acc ).
walenty(mandat , od , gen ).
walenty(mandat , o , loc ).
walenty(mandat , za , acc ).
walenty(mandat , z , acc ).
walenty(marzenie , o , loc ).
walenty(materiał , dla , gen ).
walenty(materiał , do , gen ).
walenty(materiał , na , acc ).
walenty(materiał , o , loc ).
walenty(materiał , przeciw , dat ).
walenty(mecz , między , inst ).
walenty(mecz , o , acc ).
walenty(mecz , z , inst ).
walenty(medal , dla , gen ).
walenty(medal , na , acc ).
walenty(medal , w , loc ).
walenty(medal , za , acc ).
walenty(metoda , na , acc ).
walenty(miara , w , loc ).
walenty(miara , z , gen ).
walenty(miłość , dla , gen ).
walenty(miłość , do , gen ).
walenty(miłość , między , inst ).
walenty(miłość , wobec , gen ).
walenty(miłość , wśród , gen ).
walenty(miłość , względem , gen ).
walenty(miłość , z , inst ).
walenty(minuta , po , loc ).
walenty(minuta , przed , inst ).
walenty(mistrz , w , acc ).
walenty(mistrz , w , loc ).
walenty(moda , na , acc ).
walenty(modlitwa , do , gen ).
walenty(modlitwa , nad , inst ).
walenty(modlitwa , o , acc ).
walenty(modlitwa , za , acc ).
walenty(moment , na , acc ).
walenty(moment , w , loc ).
walenty(moment , z , gen ).
walenty(most , między , inst ).
walenty(motyw , do , gen ).
walenty(motyw , o , loc ).
walenty(motyw , z , gen ).
walenty(mowa , dla , gen ).
walenty(mowa , do , gen ).
walenty(mowa , o , loc ).
walenty(mowa , przeciw , dat ).
walenty(mowa , za , inst ).
walenty(myśl , o , loc ).
walenty(nacisk , na , acc ).
walenty(nacisk , wobec , gen ).
walenty(nacisk , względem , gen ).
walenty(nadzieja , dla , gen ).
walenty(nadzieja , na , acc ).
walenty(nadzieja , w , loc ).
walenty(nadzór , nad , inst ).
walenty(nadzór , wobec , gen ).
walenty(nadzór , względem , gen ).
walenty(nakład , dla , gen ).
walenty(nakład , na , acc ).
walenty(namiętność , do , gen ).
walenty(namiętność , między , inst ).
walenty(namiętność , w , loc ).
walenty(namiętność , wobec , gen ).
walenty(namiętność , względem , gen ).
walenty(napad , na , acc ).
walenty(napad , z , inst ).
walenty(napis , o , loc ).
walenty(napis , z , inst ).
walenty(narzędzie , dla , gen ).
walenty(narzędzie , do , gen ).
walenty(nauka , o , loc ).
walenty(nic , do , gen ).
walenty(nic , po , loc ).
walenty(nic , z , gen ).
walenty(niebezpieczeństwo , dla , gen ).
walenty(niechęć , dla , gen ).
walenty(niechęć , do , gen ).
walenty(niechęć , między , inst ).
walenty(nienawiść , do , gen ).
walenty(nienawiść , między , inst ).
walenty(nienawiść , wobec , gen ).
walenty(niepokój , o , acc ).
walenty(niepokój , przed , inst ).
walenty(niepokój , wobec , gen ).
walenty(niepokój , wokół , gen ).
walenty(nieprawda , o , loc ).
walenty(norma , dla , gen ).
walenty(norma , w , loc ).
walenty(numer , o , loc ).
walenty(nurt , w , loc ).
walenty(obawa , o , acc ).
walenty(obawa , przed , inst ).
walenty(obawa , wobec , gen ).
walenty(obietnica , dla , gen ).
walenty(obietnica , wobec , gen ).
walenty(obietnica , względem , gen ).
walenty(obowiązek , wobec , gen ).
walenty(obowiązek , względem , gen ).
walenty(obóz , dla , gen ).
walenty(obrona , od , gen ).
walenty(obrona , przeciw , dat ).
walenty(obrona , przed , inst ).
walenty(obrona , przez , acc ).
walenty(obserwacja , nad , inst ).
walenty(ochota , do , gen ).
walenty(ochota , na , acc ).
walenty(ochrona , dla , gen ).
walenty(ochrona , przeciw , dat ).
walenty(ochrona , przed , inst ).
walenty(ochrona , wobec , gen ).
walenty(odbiór , przez , acc ).
walenty(odbiór , z , gen ).
walenty(odkrycie , przez , acc ).
walenty(odkrycie , w , loc ).
walenty(odmiana , dla , gen ).
walenty(odmiana , od , gen ).
walenty(odmiana , przez , acc ).
walenty(odpowiedź , do , gen ).
walenty(odpowiedzialność , przed , inst ).
walenty(odpowiedzialność , wobec , gen ).
walenty(odpowiedzialność , za , acc ).
walenty(odpowiedź , na , acc ).
walenty(odpowiedź , o , loc ).
walenty(odwaga , do , gen ).
walenty(odwaga , na , acc ).
walenty(odwaga , w , loc ).
walenty(odwaga , wobec , gen ).
walenty(oferta , dla , gen ).
walenty(oferta , na , acc ).
walenty(ofiara , dla , gen ).
walenty(ofiara , na , acc ).
walenty(ofiara , za , acc ).
walenty(ofiara , z , gen ).
walenty(ogień , z , gen ).
walenty(ogłoszenie , o , loc ).
walenty(okazja , dla , gen ).
walenty(okazja , do , gen ).
walenty(okazja , na , acc ).
walenty(okno , do , gen ).
walenty(okno , na , acc ).
walenty(okno , od , gen ).
walenty(określenie , na , acc ).
walenty(określenie , wobec , gen ).
walenty(określenie , względem , gen ).
walenty(operacja , na , acc ).
walenty(operacja , na , loc ).
walenty(operacja , przeciw , dat ).
walenty(opieka , dla , gen ).
walenty(opieka , nad , inst ).
walenty(opinia , o , loc ).
walenty(opinia , wobec , gen ).
walenty(opinia , względem , gen ).
walenty(opłata , na , acc ).
walenty(opłata , od , gen ).
walenty(opłata , w , loc ).
walenty(opłata , za , acc ).
walenty(opór , przeciw , dat ).
walenty(opór , przed , inst ).
walenty(opór , wobec , gen ).
walenty(opór , względem , gen ).
walenty(opowieść , o , loc ).
walenty(opozycja , dla , gen ).
walenty(opozycja , do , gen ).
walenty(opozycja , między , inst ).
walenty(opozycja , przeciw , dat ).
walenty(opozycja , wobec , gen ).
walenty(opozycja , względem , gen ).
walenty(pamięć , do , gen ).
walenty(pamięć , o , loc ).
walenty(pani , na , loc ).
walenty(pani , od , gen ).
walenty(pan , na , loc ).
walenty(pan , od , gen ).
walenty(partner , do , gen ).
walenty(partner , w , loc ).
walenty(pies , do , gen ).
walenty(pies , na , acc ).
walenty(pismo , do , gen ).
walenty(pismo , o , acc ).
walenty(pismo , o , loc ).
walenty(pismo , przeciw , dat ).
walenty(pismo , za , inst ).
walenty(plan , na , acc ).
walenty(plan , wobec , gen ).
walenty(plan , względem , gen ).
walenty(plotka , o , loc ).
walenty(plotka , wokół , gen ).
walenty(pociąg , do , gen ).
walenty(pociąg , wobec , gen ).
walenty(pociąg , względem , gen ).
walenty(podejrzenie , o , acc ).
walenty(podejrzenie , wobec , gen ).
walenty(podejrzenie , względem , gen ).
walenty(podłoże , dla , gen ).
walenty(podłoże , do , gen ).
walenty(podłoże , pod , acc ).
walenty(podłoże , z , gen ).
walenty(podpis , na , loc ).
walenty(podpis , o , acc ).
walenty(podpis , o , loc ).
walenty(podpis , pod , inst ).
walenty(podpis , przeciw , dat ).
walenty(podpis , za , inst ).
walenty(podręcznik , dla , gen ).
walenty(podręcznik , do , gen ).
walenty(podręcznik , o , loc ).
walenty(podręcznik , z , inst ).
walenty(pogląd , na , acc ).
walenty(pogląd , przeciw , dat ).
walenty(pogląd , wobec , gen ).
walenty(pogląd , względem , gen ).
walenty(pogląd , za , inst ).
walenty(pogoda , dla , gen ).
walenty(pojęcie , o , loc ).
walenty(pokaz , dla , gen ).
walenty(pokaz , o , loc ).
walenty(pokaz , z , gen ).
walenty(połączenie , między , inst ).
walenty(połączenie , w , acc ).
walenty(połączenie , z , inst ).
walenty(polecenie , dla , gen ).
walenty(polecenie , do , gen ).
walenty(polecenie , od , gen ).
walenty(pole , dla , gen ).
walenty(pole , do , gen ).
walenty(pole , pod , acc ).
walenty(pomoc , dla , gen ).
walenty(pomoc , do , gen ).
walenty(pomoc , na , acc ).
walenty(pomoc , od , gen ).
walenty(pomoc , przy , loc ).
walenty(pomoc , w , loc ).
walenty(pomyłka , o , acc ).
walenty(pomyłka , w , loc ).
walenty(pomysł , na , acc ).
walenty(pomysł , o , loc ).
walenty(poparcie , dla , gen ).
walenty(poparcie , w , loc ).
walenty(poparcie , wobec , gen ).
walenty(poprawa , na , acc ).
walenty(poprawa , u , gen ).
walenty(poprawa , w , loc ).
walenty(poprawa , z , gen ).
walenty(poprawka , do , gen ).
walenty(poprawka , na , acc ).
walenty(poprawka , o , loc ).
walenty(poprawka , przeciw , dat ).
walenty(poprawka , w , loc ).
walenty(poprawka , wobec , gen ).
walenty(poprawka , względem , gen ).
walenty(poprawka , z , gen ).
walenty(porozumienie , między , inst ).
walenty(porozumienie , o , loc ).
walenty(porozumienie , przeciw , dat ).
walenty(porozumienie , z , inst ).
walenty(poseł , do , gen ).
walenty(poseł , na , acc ).
walenty(postawa , przeciw , dat ).
walenty(postawa , wobec , gen ).
walenty(postawa , względem , gen ).
walenty(postawa , za , inst ).
walenty(postęp , w , loc ).
walenty(postęp , wobec , gen ).
walenty(postęp , względem , gen ).
walenty(postulat , do , gen ).
walenty(postulat , przeciw , dat ).
walenty(postulat , za , inst ).
walenty(powód , do , gen ).
walenty(praca , dla , gen ).
walenty(praca , na , acc ).
walenty(praca , nad , inst ).
walenty(praca , na , loc ).
walenty(praca , o , loc ).
walenty(praca , przy , loc ).
walenty(praca , za , acc ).
walenty(praca , z , gen ).
walenty(praca , z , inst ).
walenty(prąd , w , loc ).
walenty(prawda , o , loc ).
walenty(prawo , dla , gen ).
walenty(prawo , do , gen ).
walenty(prawo , o , loc ).
walenty(prezent , dla , gen ).
walenty(prezent , na , acc ).
walenty(prezent , od , gen ).
walenty(prezent , pod , acc ).
walenty(problem , dla , gen ).
walenty(problem , w , loc ).
walenty(problem , z , inst ).
walenty(proces , między , inst ).
walenty(proces , o , acc ).
walenty(proces , przeciw , dat ).
walenty(proces , za , acc ).
walenty(proces , z , inst ).
walenty(prognoza , dla , gen ).
walenty(prognoza , na , acc ).
walenty(prognoza , o , loc ).
walenty(promocja , dla , gen ).
walenty(promocja , do , gen ).
walenty(promocja , na , acc ).
walenty(promocja , z , gen ).
walenty(propozycja , dla , gen ).
walenty(propozycja , do , gen ).
walenty(propozycja , na , acc ).
walenty(prośba , do , gen ).
walenty(prośba , o , acc ).
walenty(protest , do , gen ).
walenty(protest , przeciw , dat ).
walenty(protokół , do , gen ).
walenty(protokół , o , loc ).
walenty(protokół , przeciw , dat ).
walenty(protokół , z , gen ).
walenty(przejazd , na , loc ).
walenty(przejazd , w , loc ).
walenty(przekonanie , o , loc ).
walenty(przekonanie , wobec , gen ).
walenty(przekonanie , względem , gen ).
walenty(przełom , w , loc ).
walenty(przemiana , na , acc ).
walenty(przemiana , w , acc ).
walenty(przemiana , z , gen ).
walenty(przepis , na , acc ).
walenty(przepis , przeciw , dat ).
walenty(przepis , w , loc ).
walenty(przerwa , między , inst ).
walenty(przerwa , na , acc ).
walenty(przerwa , od , gen ).
walenty(przerwa , w , loc ).
walenty(przestępstwo , na , loc ).
walenty(przestępstwo , przeciw , dat ).
walenty(przestępstwo , wobec , gen ).
walenty(przestępstwo , z , inst ).
walenty(przeszkoda , dla , gen ).
walenty(przeszkoda , do , gen ).
walenty(przeszkoda , przeciw , dat ).
walenty(przeszkoda , w , loc ).
walenty(przeszkoda , z , gen ).
walenty(przyjaźń , dla , gen ).
walenty(przyjaźń , do , gen ).
walenty(przyjaźń , między , inst ).
walenty(przyjaźń , wobec , gen ).
walenty(przyjaźń , wśród , gen ).
walenty(przyjaźń , względem , gen ).
walenty(przyjaźń , z , inst ).
walenty(przyjemność , dla , gen ).
walenty(przyjemność , w , loc ).
walenty(przyjemność , z , gen ).
walenty(przykład , dla , gen ).
walenty(przykład , do , gen ).
walenty(przykład , na , acc ).
walenty(przykład , o , loc ).
walenty(przykład , przeciw , dat ).
walenty(przykład , za , inst ).
walenty(przyszłość , przed , inst ).
walenty(przyszłość , w , loc ).
walenty(pytanie , dla , gen ).
walenty(pytanie , do , gen ).
walenty(pytanie , o , acc ).
walenty(pytanie , o , loc ).
walenty(pytanie , z , gen ).
walenty(rachunek , na , acc ).
walenty(rachunek , za , acc ).
walenty(rachunek , z , gen ).
walenty(rada , dla , gen ).
walenty(rada , na , acc ).
walenty(rada , o , loc ).
walenty(radość , po , loc ).
walenty(radość , z , gen ).
walenty(reakcja , między , inst ).
walenty(reakcja , na , acc ).
walenty(reakcja , przeciw , dat ).
walenty(reakcja , wobec , gen ).
walenty(reakcja , względem , gen ).
walenty(reakcja , z , inst ).
walenty(relacja , do , gen ).
walenty(relacja , między , inst ).
walenty(relacja , o , loc ).
walenty(relacja , wobec , gen ).
walenty(relacja , wśród , gen ).
walenty(relacja , względem , gen ).
walenty(relacja , z , inst ).
walenty(rewolucja , przeciw , dat ).
walenty(rewolucja , w , loc ).
walenty(rezerwa , dla , gen ).
walenty(rezerwa , do , gen ).
walenty(rezerwa , na , acc ).
walenty(rezerwa , w , loc ).
walenty(rezerwa , wobec , gen ).
walenty(rezerwa , względem , gen ).
walenty(rola , dla , gen ).
walenty(rola , u , gen ).
walenty(rola , w , loc ).
walenty(rola , wśród , gen ).
walenty(romans , między , inst ).
walenty(romans , o , loc ).
walenty(romans , z , inst ).
walenty(roszczenie , do , gen ).
walenty(roszczenie , między , inst ).
walenty(roszczenie , o , acc ).
walenty(roszczenie , od , gen ).
walenty(roszczenie , przeciw , dat ).
walenty(roszczenie , wobec , gen ).
walenty(roszczenie , względem , gen ).
walenty(roszczenie , za , acc ).
walenty(roszczenie , z , gen ).
walenty(rozkaz , dla , gen ).
walenty(rozkaz , do , gen ).
walenty(rozkaz , o , acc ).
walenty(rozkaz , od , gen ).
walenty(różnica , między , inst ).
walenty(różnica , w , loc ).
walenty(różnica , wobec , gen ).
walenty(rozpacz , nad , inst ).
walenty(rozpacz , po , loc ).
walenty(rozpacz , za , inst ).
walenty(rozporządzenie , do , gen ).
walenty(rozporządzenie , o , loc ).
walenty(rozwiązanie , do , gen ).
walenty(rozwiązanie , na , acc ).
walenty(rozwiązanie , przeciw , dat ).
walenty(rozwiązanie , za , inst ).
walenty(runda , wokół , gen ).
walenty(rysunek , w , loc ).
walenty(ryzyko , dla , gen ).
walenty(rzecz , do , gen ).
walenty(rzecz , w , loc ).
walenty(sąd , nad , inst ).
walenty(sąd , o , loc ).
walenty(satysfakcja , z , gen ).
walenty(scenariusz , do , gen ).
walenty(scenariusz , na , acc ).
walenty(scenariusz , o , loc ).
walenty(seminarium , dla , gen ).
walenty(seminarium , o , loc ).
walenty(seminarium , u , gen ).
walenty(seminarium , z , gen ).
walenty(seria , o , loc ).
walenty(seria , z , gen ).
walenty(seria , z , inst ).
walenty(skarga , do , gen ).
walenty(skarga , na , acc ).
walenty(skarga , o , acc ).
walenty(skarga , przeciw , dat ).
walenty(skłonność , do , gen ).
walenty(skok , na , loc ).
walenty(skok , w , loc ).
walenty(skok , z , inst ).
walenty(skutek , dla , gen ).
walenty(ślad , od , gen ).
walenty(ślad , po , loc ).
walenty(śmiech , z , gen ).
walenty(smutek , po , loc ).
walenty(sojusz , między , inst ).
walenty(sojusz , przeciw , dat ).
walenty(sojusz , z , inst ).
walenty(solidarność , dla , gen ).
walenty(solidarność , między , inst ).
walenty(solidarność , w , loc ).
walenty(solidarność , wobec , gen ).
walenty(solidarność , względem , gen ).
walenty(solidarność , z , inst ).
walenty(spacer , z , inst ).
walenty(spadek , na , loc ).
walenty(spadek , o , acc ).
walenty(spadek , po , loc ).
walenty(spadek , w , loc ).
walenty(specjalista , do , gen ).
walenty(specjalista , od , gen ).
walenty(specjalista , w , loc ).
walenty(specjalista , z , gen ).
walenty(spór , między , inst ).
walenty(spór , o , acc ).
walenty(spór , wokół , gen ).
walenty(spór , z , inst ).
walenty(sprawozdanie , do , gen ).
walenty(sprawozdanie , o , loc ).
walenty(sprawozdanie , z , gen ).
walenty(sprzeciw , dla , gen ).
walenty(sprzeciw , od , gen ).
walenty(sprzeciw , wobec , gen ).
walenty(stanowisko , dla , gen ).
walenty(stanowisko , pod , acc ).
walenty(stanowisko , przeciw , dat ).
walenty(stanowisko , wobec , gen ).
walenty(stanowisko , względem , gen ).
walenty(stanowisko , za , inst ).
walenty(staranie , o , acc ).
walenty(staranie , o , loc ).
walenty(strach , o , acc ).
walenty(strach , przed , inst ).
walenty(strach , wobec , gen ).
walenty(strata , dla , gen ).
walenty(strata , do , gen ).
walenty(strata , na , loc ).
walenty(strata , w , loc ).
walenty(strategia , dla , gen ).
walenty(strategia , na , acc ).
walenty(strategia , przeciw , dat ).
walenty(strategia , wobec , gen ).
walenty(strategia , względem , gen ).
walenty(strzał , z , gen ).
walenty(stwierdzenie , o , loc ).
walenty(sukces , dla , gen ).
walenty(sukces , w , loc ).
walenty(świadectwo , dla , gen ).
walenty(świadectwo , na , acc ).
walenty(świadectwo , o , loc ).
walenty(świadectwo , przeciw , dat ).
walenty(świadectwo , wobec , gen ).
walenty(świadectwo , z , gen ).
walenty(świadomość , o , loc ).
walenty(swoboda , do , gen ).
walenty(swoboda , od , gen ).
walenty(swoboda , w , loc ).
walenty(sympatia , dla , gen ).
walenty(sympatia , do , gen ).
walenty(sympatia , między , inst ).
walenty(szacunek , dla , gen ).
walenty(szacunek , do , gen ).
walenty(szacunek , między , inst ).
walenty(szacunek , o , loc ).
walenty(szacunek , wobec , gen ).
walenty(szczęście , do , gen ).
walenty(szczęście , w , loc ).
walenty(szok , dla , gen ).
walenty(sztuka , dla , gen ).
walenty(sztuka , o , loc ).
walenty(sztuka , w , loc ).
walenty(talent , do , gen ).
walenty(telefon , o , loc ).
walenty(telefon , z , inst ).
walenty(tendencja , do , gen ).
walenty(tendencja , w , loc ).
walenty(teoria , o , loc ).
walenty(test , dla , gen ).
walenty(test , na , acc ).
walenty(test , na , loc ).
walenty(test , z , gen ).
walenty(test , z , inst ).
walenty(teza , o , loc ).
walenty(teza , przeciw , dat ).
walenty(teza , za , inst ).
walenty(tolerancja , dla , gen ).
walenty(tolerancja , między , inst ).
walenty(tolerancja , na , acc ).
walenty(tolerancja , przez , acc ).
walenty(tolerancja , wobec , gen ).
walenty(tolerancja , względem , gen ).
walenty(tom , dla , gen ).
walenty(tom , o , loc ).
walenty(tom , przeciw , dat ).
walenty(tom , w , loc ).
walenty(tom , z , gen ).
walenty(tradycja , o , loc ).
walenty(tragedia , o , loc ).
walenty(tragedia , z , inst ).
walenty(troska , o , acc ).
walenty(trudność , dla , gen ).
walenty(trudność , przy , loc ).
walenty(trudność , w , loc ).
walenty(trudność , z , inst ).
walenty(trud , w , loc ).
walenty(tytuł , dla , gen ).
walenty(tytuł , do , gen ).
walenty(uczucie , dla , gen ).
walenty(uczucie , do , gen ).
walenty(uczucie , między , inst ).
walenty(uczucie , wobec , gen ).
walenty(uczucie , względem , gen ).
walenty(udział , w , loc ).
walenty(udział , z , gen ).
walenty(umowa , między , inst ).
walenty(umowa , na , acc ).
walenty(umowa , o , acc ).
walenty(umowa , o , loc ).
walenty(umowa , przeciw , dat ).
walenty(umowa , z , inst ).
walenty(uprawnienie , do , gen ).
walenty(uprawnienie , w , loc ).
walenty(ustawa , o , loc ).
walenty(ustawa , przeciw , dat ).
walenty(wada , w , loc ).
walenty(walka , między , inst ).
walenty(walka , na , acc ).
walenty(walka , o , acc ).
walenty(walka , przeciw , dat ).
walenty(walka , z , inst ).
walenty(wdowa , po , loc ).
walenty(wersja , dla , gen ).
walenty(wersja , o , loc ).
walenty(wiara , w , acc ).
walenty(widok , na , acc ).
walenty(wiedza , o , loc ).
walenty(wiedza , z , gen ).
walenty(wiersz , dla , gen ).
walenty(wiersz , ku , dat ).
walenty(wiersz , na , acc ).
walenty(wiersz , o , loc ).
walenty(wiersz , przeciw , dat ).
walenty(wina , przeciw , dat ).
walenty(wina , w , loc ).
walenty(wina , wobec , gen ).
walenty(wina , względem , gen ).
walenty(wina , za , acc ).
walenty(wizja , dla , gen ).
walenty(wizja , o , loc ).
walenty(wizyta , z , inst ).
walenty(władza , nad , inst ).
walenty(władza , w , loc ).
walenty(wniosek , do , gen ).
walenty(wniosek , na , acc ).
walenty(wniosek , o , acc ).
walenty(wniosek , przeciw , dat ).
walenty(wniosek , za , inst ).
walenty(wniosek , z , gen ).
walenty(wojna , między , inst ).
walenty(wojna , o , acc ).
walenty(wojna , przeciw , dat ).
walenty(wojna , z , inst ).
walenty(wola , do , gen ).
walenty(wola , wobec , gen ).
walenty(wola , względem , gen ).
walenty(wrażenie , z , inst ).
walenty(wspólnik , w , loc ).
walenty(wspomnienie , o , loc ).
walenty(wspomnienie , po , loc ).
walenty(wspomnienie , sprzed , gen ).
walenty(wspomnienie , z , gen ).
walenty(wstęp , do , gen ).
walenty(wstęp , o , loc ).
walenty(wycieczka , na , loc ).
walenty(wyjaśnienie , dla , gen ).
walenty(wyjaśnienie , do , gen ).
walenty(wyjaśnienie , o , loc ).
walenty(wyjątek , od , gen ).
walenty(wyjątek , wobec , gen ).
walenty(wyjątek , względem , gen ).
walenty(wyjątek , z , gen ).
walenty(wynik , w , loc ).
walenty(wynik , z , inst ).
walenty(wyrok , dla , gen ).
walenty(wyrok , na , acc ).
walenty(wyrok , o , acc ).
walenty(wyrok , o , loc ).
walenty(wyrok , przeciw , dat ).
walenty(wyrok , w , loc ).
walenty(wyrok , za , acc ).
walenty(wysiłek , dla , gen ).
walenty(wysiłek , nad , inst ).
walenty(wysiłek , przeciw , dat ).
walenty(wysiłek , przy , loc ).
walenty(wysiłek , wobec , gen ).
walenty(wysiłek , wokół , gen ).
walenty(wysiłek , względem , gen ).
walenty(wywiad , dla , gen ).
walenty(wywiad , o , loc ).
walenty(wywiad , z , inst ).
walenty(wzgląd , dla , gen ).
walenty(wzgląd , na , acc ).
walenty(wzgląd , u , gen ).
walenty(wzgląd , wobec , gen ).
walenty(zabawa , dla , gen ).
walenty(zabawa , na , loc ).
walenty(zabawa , przy , loc ).
walenty(zabawa , w , acc ).
walenty(zabawa , z , inst ).
walenty(zabieg , na , acc ).
walenty(zabieg , na , loc ).
walenty(zabieg , o , acc ).
walenty(zabieg , z , gen ).
walenty(żądanie , o , acc ).
walenty(żądanie , od , gen ).
walenty(żałoba , po , loc ).
walenty(założenie , do , gen ).
walenty(założenie , o , loc ).
walenty(założenie , przez , acc ).
walenty(zamach , na , acc ).
walenty(zamach , przeciw , dat ).
walenty(zamiar , przeciw , dat ).
walenty(zamiar , wobec , gen ).
walenty(zamiar , względem , gen ).
walenty(zapowiedź , o , loc ).
walenty(żart , o , loc ).
walenty(żart , wobec , gen ).
walenty(żart , wokół , gen ).
walenty(żart , względem , gen ).
walenty(żart , z , gen ).
walenty(zarząd , nad , inst ).
walenty(zasada , o , loc ).
walenty(zasiłek , dla , gen ).
walenty(zasiłek , na , acc ).
walenty(zasługa , dla , gen ).
walenty(zasługa , przy , loc ).
walenty(zasługa , w , loc ).
walenty(zasługa , wobec , gen ).
walenty(zastrzeżenie , do , gen ).
walenty(zastrzeżenie , wobec , gen ).
walenty(zastrzeżenie , względem , gen ).
walenty(zaufanie , dla , gen ).
walenty(zaufanie , do , gen ).
walenty(zaufanie , między , inst ).
walenty(zaufanie , wobec , gen ).
walenty(zaufanie , wśród , gen ).
walenty(zaufanie , względem , gen ).
walenty(zawartość , w , loc ).
walenty(zawód , dla , gen ).
walenty(zawód , o , acc ).
walenty(zawód , w , acc ).
walenty(zawód , w , loc ).
walenty(zawody , między , inst ).
walenty(zawody , o , acc ).
walenty(zawody , w , acc ).
walenty(zawody , w , loc ).
walenty(zbrodnia , na , loc ).
walenty(zbrodnia , przeciw , dat ).
walenty(zbrodnia , wobec , gen ).
walenty(zbrodnia , z , inst ).
walenty(zeznanie , o , loc ).
walenty(zeznanie , przeciw , dat ).
walenty(zeznanie , za , acc ).
walenty(zeznanie , z , gen ).
walenty(zgoda , między , inst ).
walenty(zgoda , na , acc ).
walenty(zgoda , z , inst ).
walenty(złość , między , inst ).
walenty(złość , na , acc ).
walenty(złość , przeciw , dat ).
walenty(złość , wobec , gen ).
walenty(złość , wśród , gen ).
walenty(złość , względem , gen ).
walenty(złość , za , acc ).
walenty(złudzenie , wobec , gen ).
walenty(złudzenie , względem , gen ).
walenty(znajomość , między , inst ).
walenty(znajomość , z , inst ).
walenty(znak , dla , gen ).
walenty(znak , do , gen ).
walenty(znak , po , loc ).
walenty(związek , między , inst ).
walenty(związek , z , inst ).
walenty(zwycięstwo , nad , inst ).
walenty(zwycięstwo , przeciw , dat ).
walenty(zwycięstwo , w , loc ).
walenty(zwycięstwo , z , inst ).
walenty(życzenie , dla , gen ).
walenty(życzenie , od , gen ).
walenty(zysk , dla , gen ).
walenty(zysk , od , gen ).
walenty(zysk , za , acc ).
walenty(zysk , z , gen ).